### ISSUE TITLE
502 During Web Socket Handshake

### ISSUE THREAD

**Issue by rmorshea** [jupyterhub/jupyter-server-proxy#39] opened 2018-06-17 08:08 UTC
I'm trying to get web sockets to work when running a [Sanic](http://sanic.readthedocs.io/en/latest/sanic/routing.html#websocket-routes) server via proxy on https://mybinder.org.

I don't think I know enough to understand whether or not the 502 Bad Gateway is resulting from a problem with Sanic or with nbserverproxy (or the way I've configured either). Is this a common issue? If not, what information do I need in order to debug this?

@ryanlovett I noticed that you worked on the socket proxy logic - any thoughts?

**Comment by ryanlovett** [comment] 2018-06-19 00:13
Hi @rmorshea , do you have an example Sanic server? I haven't received other reports of Sanic servers, good or bad.

I tried https://github.com/Enforcer/simple-chat with the patch below and it worked for me on a JupyterHub instance. I'll try on binder.
```
--- static/index.html.orig	2018-06-18 17:11:07.000000000 -0700
+++ static/index.html	2018-06-18 17:10:58.000000000 -0700
@@ -63,7 +63,8 @@


 $(function() {
-    websocket = new WebSocket('ws://127.0.0.1:8000/chat');
+    var url = 'wss://' + document.location.hostname + document.location.pathname + '/chat';
+    websocket = new WebSocket(url);
     websocket.onopen = init(websocket);
     websocket.onerror = websocket.onclose = close;
     websocket.onmessage = newMessage;
```

**Comment by ryanlovett** [comment] 2018-06-19 00:22
Works on binder too, https://mybinder.org/v2/gh/ryanlovett/simple-chat/master. Start server.py in a terminal and visit proxy/8000.

That being said, maybe nbserverproxy isn't doing the right thing for more complicated ws apps.

**Comment by joshbode** [comment] 2018-07-30 02:34
I think I'm seeing something similar with kubernetes + jupyterhub + jupyterlab + nbserverproxy + dask:

From the jupyterlab logs:
```
[I 2018-07-30 02:05:10.484 SingleUserLabApp log:158] 200 GET /user/josh.bode/proxy/35902/status (josh.bode@10.142.0.6) 123.54ms
[I 2018-07-30 02:05:12.053 SingleUserLabApp handlers:299] Client sent subprotocols: []
Future exception was never retrieved
future: <Future finished exception=IndexError('list index out of range',)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/lib/python3.6/site-packages/tornado/websocket.py", line 721, in _accept_connection
    self.selected_subprotocol = self.handler.select_subprotocol(subprotocols)
  File "/opt/conda/lib/python3.6/site-packages/nbserverproxy/handlers.py", line 300, in select_subprotocol
    return subprotocols[0]
IndexError: list index out of range
[I 2018-07-30 02:05:12.054 SingleUserLabApp log:158] 200 GET /user/josh.bode/proxy/35902/status/ws?bokeh-protocol-version=1.0&bokeh-session-id=e5kkptP2bwJfvcqUw15vgIFmwDuOeoOQQ9xfiIgnq20H (josh.bode@10.142.0.6) 3.03ms
```

## Versions
```
jupyterhub==0.9.1
jupyterlab==0.32.1
nbserverproxy==0.8.3
tornado==5.1
dask==0.18.2
dask-kubernetes==0.4.0
```

**Comment by joshbode** [comment] 2018-07-30 02:50
Downgrading to Tornado 5.0 worked for me.

See http://www.tornadoweb.org/en/stable/releases/v5.1.0.html#tornado-websocket
> The WebSocketHandler.select_subprotocol method is now called with an empty list instead of a list containing an empty string if no subprotocols were requested by the client.

**Comment by jakirkham** [comment] 2018-08-20 13:57
Those of you who are using Dask, did you see something like this? Was that fixed with PR ( https://github.com/jupyterhub/nbserverproxy/pull/44 ).

<img width="1552" alt="screen shot 2018-08-20 at 09 30 29" src="https://user-images.githubusercontent.com/3019665/44344706-52a20b80-a45f-11e8-9c06-2182d7993a06.png">

**Comment by jakirkham** [comment] 2018-08-20 14:11
Those of you who are using Dask, did you see something like this? Was that fixed with PR ( https://github.com/jupyterhub/nbserverproxy/pull/44 ).

<img width="1440" alt="screen shot 2018-08-20 at 09 30 29" src="https://user-images.githubusercontent.com/3019665/44344822-9dbc1e80-a45f-11e8-9ee1-0a460d890a1f.png">

**Comment by joshbode** [comment] 2018-08-20 22:00
Yes - that's what I was getting, and what drove the PR. Should work after updating (not sure if the change is packaged, though)

**Comment by joshbode** [comment] 2018-08-20 22:14
Looks like #44 isn't part of the latest package yet (latest on PyPI is 0.8.3 from May) - can a new version be released, please? :)

**Comment by jakirkham** [comment] 2018-11-03 05:54
As this is fixed and there have been a couple of releases since, should this be closed?

**Comment by rmorshea** [comment] 2019-04-01 09:29
@jakirkham I'm still encountering this problem.

**Comment by rmorshea** [comment] 2019-04-01 09:41
@betatim any idea how I can get logs from Jupyter out of a binder instance so I can try to debug this websocket 502 error?

**Comment by betatim** [comment] 2019-04-01 09:46
I'd run http://repo2docker.readthedocs.io/ locally. That gives you access to more of the logs and faster turn around than using mybinder.org: `repo2docker https://github.com/<org>/<repo>` basically does what launching that repo does on mybinder.org.

**Comment by rmorshea** [comment] 2019-04-01 09:54
@betatim thanks I'll try that out.

**Comment by rmorshea** [comment] 2019-04-02 07:36
@betatim so I tried out repo2docker and everything seemed to work great. It really seems like this is something that needs to be debugged on binderhub.

**Comment by betatim** [comment] 2019-04-02 10:28
Do you have a link I can click to launch your binder and how to reproduce the error? Websockets working locally but not "over the internet" makes me think "there is a proxy server/firewall in the middle" but usually when that is the case notebooks also don't manage to establish a websocket connection.

To get more logs on mybinder.org you can [add a `start` file](https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts) that `tee`'s the logs or some such. At least that is what I'd try.

**Comment by rmorshea** [comment] 2019-04-02 15:51
@betatim you should be able to run this notebook and see a 502 error in the javascript console.

**Comment by betatim** [comment] 2019-04-02 18:39
Thanks. I unfortunately don't know enough about how websockets work and what idiom does to help you from what I can see. What does the log say when you pipe it to a file maybe there is a hint in there about what is going wrong. Otherwise I'd post on discourse.jupyter.org to see if someone there can help you.

**Comment by betatim** [comment] 2019-04-02 19:05
This is the log you get via being an admin for mybinder.org:
```
[I 18:58:53.391 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[I 18:58:55.114 NotebookApp] JupyterLab extension loaded from /srv/conda/lib/python3.7/site-packages/jupyterlab
[I 18:58:55.114 NotebookApp] JupyterLab application directory is /srv/conda/share/jupyter/lab
[I 18:58:55.122 NotebookApp] nteract extension loaded from /srv/conda/lib/python3.7/site-packages/nteract_on_jupyter
[I 18:58:55.124 NotebookApp] Will shut down after 600 seconds with no kernels or terminals.
[I 18:58:55.124 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 18:58:55.124 NotebookApp] The Jupyter Notebook is running at:
[I 18:58:55.124 NotebookApp] http://(jupyter-rmorshea-2didom-2dv5f5yuxg or 127.0.0.1):8888/user/rmorshea-idom-v5f5yuxg/?token=...
[I 18:58:55.124 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 18:58:55.129 NotebookApp] No web browser found: could not locate runnable browser.
[I 18:58:58.524 NotebookApp] 302 GET /user/rmorshea-idom-v5f5yuxg/ (10.12.3.27) 1.17ms
[I 18:59:02.123 NotebookApp] 302 GET /user/rmorshea-idom-v5f5yuxg/tree/examples/introduction.ipynb?token=jeeR7SKSTOWYwQt29aaR4A (31.10.137.11) 3.67ms
[I 18:59:04.800 NotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[W 18:59:04.802 NotebookApp] Notebook examples/introduction.ipynb is not trusted
[I 18:59:05.336 NotebookApp] Kernel started: ec289b32-bf13-4696-86f6-32d247ef5beb
[I 18:59:05.337 NotebookApp] Culling kernels with idle durations > 600 seconds at 60 second intervals ...
[I 18:59:05.338 NotebookApp] Culling kernels even with connected clients
[I 18:59:07.286 NotebookApp] Adapting to protocol v5.1 for kernel ec289b32-bf13-4696-86f6-32d247ef5beb
[I 19:01:05.291 NotebookApp] Saving file at /examples/introduction.ipynb
/srv/conda/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py:89: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super().get(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[I 19:03:05.914 NotebookApp] Saving file at /examples/introduction.ipynb
```

The last error sounds like a problem in jupyter server proxy that should also appear locally. To fix it, it should be as easy as adding a `await` on the line.

**Comment by rmorshea** [comment] 2019-04-02 19:08
@betatim thanks for debugging that for me. It's not clear to me why it ran locally though...

**Comment by rmorshea** [comment] 2019-04-06 04:47
@betatim it looks like this was part of Tornado v6.0.2:

https://github.com/tornadoweb/tornado/commit/e69becbf8c994be5bfa6584ef72df594b27934b5

**Comment by rmorshea** [comment] 2019-04-06 19:09
Finally got a chance to try out my repo with the patch and can confirm that this fixes my issues.

**Closed** 2019-04-08 07:29 UTC
