### ISSUE TITLE
Document how to debug/ how to find logs

### ISSUE THREAD

**Issue by MarcSkovMadsen** [jupyterhub/jupyter-server-proxy#319] opened 2022-02-05 06:36 UTC
Hi

I've been using the jupyter-server-proxy several times. When it works its really, really great. 

Initially though there can be some hazzles. I develop on windows. And it does not work on windows.

```
 File "C:\Users\masma\Anaconda3\envs\panel_vegafusion\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
        raise NotImplementedError
```

Thus I cannot debug locally. I'm sort of blind. 

Ok but normally the goal is to get it working on Binder. I use Binder to make it easy for users to explore the open source packages I develop. But on Binder I'm sort of blind again if something goes wrong. 

I simply cannot get any feedback why my application is not showing up in the browser. I've trying googling for information on where to find logs. But with out luck.

My request is **please document how to debug including how to find logs (on binder)**

Thanks.

**Comment by MarcSkovMadsen** [comment] 2022-02-05 06:58
A reproducible example where I cannot get things working is this

https://mybinder.org/v2/gh/MarcSkovMadsen/panel-vegafusion/bd288bfbe6312292929269aec88ce07550dcad56?urlpath=lab

![image](https://user-images.githubusercontent.com/42288570/152632174-e66360e9-8b5f-4d04-90af-b143aa32d25c.png)

![image](https://user-images.githubusercontent.com/42288570/152632186-7ab3aa4a-e7ce-419b-bacb-167230e825cb.png)

I need server side logs to understand why nothing is showing up. How do I find them?

**Comment by manics** [comment] 2022-02-05 12:02
This is a duplicate of https://discourse.jupyter.org/t/how-do-i-find-the-logs-of-the-jupyter-server-proxy-for-debugging/12904

**Closed** 2022-02-05 12:02 UTC
Labels: support
