### ISSUE TITLE
ERROR '_xsrf' argument missing from POST when trying to run notebook in jupyterlab when my proxying processes app is active

### ISSUE THREAD

**Issue by sham-sr** [jupyterhub/jupyter-server-proxy#253] opened 2021-02-25 15:41 UTC
I'm trying to proxy streamlit.My __init.py__
```
import os
from dotenv import load_dotenv

def setup_streamlit_web():
    def _streamlit_web_command():
        env_path=os.getenv("HOME")+"/dev_env/.env"
        load_dotenv(dotenv_path=env_path)
        work_app = os.getenv("STREAMLIT_APP")
        print('streamlit app path: ', work_app)
        return ['streamlit', 'run', work_app, '--server.port', str(port)]
    return {
        'command': _streamlit_web_command,
        'environment': {},
        'timeout': 20,
        'launcher_entry': {
            'title': 'streamlit_web',
            'icon_path': os.path.join(os.path.dirname(os.path.abspath(__file__)), 'icons', 'streamlit_web.svg')
        }
    }
```
It works, but when i try to open notebook or terminal have error. Until I update my browser F5.

[I 2021-02-25 15:20:57.229 ServerApp] Trying to establish websocket connection to ws://localhost:51771/stream
[I 2021-02-25 15:20:57.237 ServerApp] Websocket connection established to ws://localhost:51771/stream
[W 2021-02-25 15:21:41.204 ServerApp] 403 POST /api/contents/work/streamlitapp?1614266499560 (172.29.0.2): '_xsrf' argument missing from POST
[W 2021-02-25 15:21:41.205 ServerApp] '_xsrf' argument missing from POST
[W 2021-02-25 15:21:41.206 ServerApp] 403 POST /api/contents/work/streamlitapp?1614266499560 (172.29.0.2) 3.19ms referer=https://jupyter.promanalysis.ru/lab
![proxy](https://user-images.githubusercontent.com/35761166/109177554-c0a2b880-77a9-11eb-95cc-1ef9d9768be1.png)

**Comment by sham-sr** [comment] 2021-02-26 19:38
https://github.com/streamlit/streamlit/issues/2517   It looks like it's streamlit erasing the cookies

**Comment by manics** [comment] 2021-02-26 19:44
Thanks for updating the issue. Since the problem is in streamlit I'll close this.

**Closed by manics** 2021-02-26 19:44 UTC
